(function buildExactRules() {
  "use strict";
  var root = typeof globalThis !== "undefined" ? globalThis : this;
  var compiler = root.UncensoredRuleCompiler ||
    (typeof require === "function" ? require("../rules-compiler") : null);
  var set = compiler.set;
  var pattern = compiler.pattern;
  var patterns = compiler.patterns;
  var group = compiler.group;
  var parts = root.UncensoredRuleDataParts;
  var vocabulary = parts.language;
  var POSSESSIVE_DETERMINERS = vocabulary.POSSESSIVE_DETERMINERS;
  var EVALUATIVE_NOUN_PREFIXES = vocabulary.EVALUATIVE_NOUN_PREFIXES;
  var EVALUATIVE_NOUN_SUFFIXES = vocabulary.EVALUATIVE_NOUN_SUFFIXES;
  var CONTEXTUAL_FUCKING_PREFIXES = set("contextual fucking prefix", [
    "like * it's", "it like a", "like it's a", "with like a", "not * my", "to build *",
    "out of a", "so * it's", "them in *", "is * just", "it * not", "middle * the",
    "you * for", "like * you're", "and it's a", "and * it's", "you get a",
    "like it was", "and he just", "and then just", "i * one", "to * i'm",
    "i bought *", "to get a", "and it is", "it's not a", "because of the", "the size *",
    "that's a good", "this is like", "it and then", "that in the", "on * just", "in * i'm",
    "it * for", "nobody's * to", "laughter * just", "size of *", "went off *",
    "when * were", "i * they", "all time *", "that * it's", "i'm in the", "like they just",
    "know * you're", "a like *", "you like a", "at like the", "to talk about", "man that's a",
    "a * it's", "just * i'm", "so * to", "me * to", "that * never", "a * on", "he'd * like",
    "then they're *", "out so *", "down in *", "down the *", "like i've *",
    "right it's *", "looking like a", "my * that's", "better * a", "not touching *", "it took *",
    "what was the", "to hit the", "it's * you're", "and * uh", "god it's *", "00 in the",
    "on * stupid", "a completely *", "a different",
    "completely different", "literally a", "for like", "you better", "around the", "and i'm",
    "i'm in", "in like", "any other", "literally just", "because i'm", "might be", "no more",
    "is he", "just started", "god it's", "found a", "your stupid", "then uh", "just kept",
    "when you're", "was completely", "everything's *", "because you're", "you're doing",
    "if i'm", "welcome to", "out you", "pull the", "that sounds", "where it", "i'm still",
    "go it's", "use a", "that to", "hours of", "a wild", "it's completely", "see your",
    "an actual", "be in", "write a", "yeah i'm", "watched the", "doctor *", "change the",
    "this in", "these like", "past the", "weird looking", "did like", "yes i", "you would",
    "i've never", "have never", "it's too", "had the", "a good", "starts", "couldn't",
    "incredibly", "weren't", "400", "barely", "possibly", "smallest", "nat",
    "everybody's", "kept", "bought"
  ]);
  var CONTEXTUAL_SHIT_PREFIXES = set("contextual shit prefix", [
    "fucking * as", "some * and", "all of that", "fucking love that", "some weird *",
    "saying the *", "sorts of *", "was a bit", "most fucked up",
    "people * that", "everything's * to", "weird * and", "took a *", "through * and",
    "of other *", "to it oh", "say * oh", "can't * see", "and * eat",
    "i * doing", "all gone *", "was some *", "the * new", "getting * and",
    "by * and", "20 * oh", "trees and", "of random", "some up", "of oh",
    "fucked up", "some wild", "fuck up", "games and", "doing other", "i sure",
    "always been", "some funny", "and goes", "uncomfortable *", "tweet *", "bushes *",
    "of new", "walls and", "rad as", "ape", "spooky", "goofy", "cowboy", "marvel",
    "heinous", "liquid", "burn", "ho", "lamest", "lighting", "spy", "dodgy", "selling"
  ]);
  var CONTEXTUAL_FUCK_PREFIXES = set("contextual fuck prefix", [
    "come * oh", "and go oh", "a * as", "and * said",
    "in * yeah", "couldn't give a", "was * called", "thing * oh",
    "would * oh", "cuz * oh", "the * f", "you're like well", "doesn't it *", "whoever the",
    "as all", "* ugh", "don't care", "that's fine", "metal as", "wall oh",
    "pop pop", "pass the", "excellent *", "pop"
  ]);

  // Phrase-specific contexts stay separate from reusable grammar.
  var EXACT_RULES = Object.freeze([
    group("exact/context-prefixes", 1000, [
      pattern`${CONTEXTUAL_FUCKING_PREFIXES} [fucking]`,
      pattern`${CONTEXTUAL_SHIT_PREFIXES} [shit]`,
      pattern`${CONTEXTUAL_FUCK_PREFIXES} [fuck]`
    ]),

    group("exact/context-two-sided", 1010, [
      pattern`and [shit] ${["where", "in", "as", "now", "you're", "talking", "that was"]}`,
      pattern`to [fucking] ${["make", "put", "think", "eat", "end", "come", "see"]}`,
      pattern`where the [fuck] ${["i", "was", "it", "that"]}`,
      pattern`the [fucking] ${["box", "end", "big", "ice", "stairs"]}`,
      pattern`oh [fuck] ${["what was", "yeah oh", "no no no"]}`,
      pattern`of [shit] ${["yeah", "because", "done", "in"]}`,
      pattern`just [fucking] ${["kill", "a", "leave", "with you"]}`,
      pattern`like [fuck] ${["me", "these"]}`,
      pattern`well [fuck] it`,
      pattern`this [shit] ${["because", "that's"]}`,
      pattern`a [fucking] ${["little", "black", "big"]}`,
      pattern`i [fucked] something up`,
      pattern`i [fucking] ${["don't", "can't", "said"]}`,
      pattern`my [shit] ${["and i", "in"]}`,
      pattern`for [fucking] ${["ever", "the"]}`,
      pattern`the [fuck] ${["it is", "was i"]}`,
      pattern`all the [shit] ${["that's", "you"]}`,
      pattern`because [fuck] it`,
      pattern`it the [fuck] out`,
      pattern`the the [fucking] the`,
      pattern`know [fuck] it`,
      pattern`of the [shit] that`,
      pattern`fine [fuck] you`,
      pattern`[fucking] thing *`,
      pattern`[fuck] it we're *`,
      pattern`[shit] off of`,
      pattern`[fucking] hate *`,
      pattern`[shit] s not`
    ]),

    group("exact/context-windows/compact", 1020, patterns([
      "oh [fuck] me *", "and [shit] and *", "* matt oh [shit]", "ah [fuck] it *", "* actually [fuck] it",
      "* brennan oh [shit]", "[fuck] it we'll *", "* [fuck] it i'll", "* and [shit] so", "yeah * [shit] s",
      "* taliesin [fuck] it", "* travis oh [shit] ashley", "all * [shit] s", "and [shit] it's",
      "[shit] s * down", "and [shit] i *", "* oh travis oh [shit]", "[shit] s crazy *", "* [fuck] it we're",
      "no [shit] yeah *", "* aabria oh [shit]", "sam oh [shit] travis", "i was like [fuck] yeah",
      "being here what's up [bitches]", "anyway [fuck] *", "* [fuck] some up", "sam [shit] matt *",
      "* taliesin [fuck] me", "* ashley [fuck] yes", "* laughs oh [shit]", "[shit] s so", "know [shit] s",
      "oh [shit] actually", "that [shit] s like", "sam oh [shit] matt", "* [shit] alexander", "[fuck] it fuck *",
      "[fuck] it i'm *", "* [fuck] you laughter", "* [shit] travis oh", "okay [fuck] it *", "right [fuck] it *",
      "oh [shit] luis *", "liam [fuck] it *", "* laura [fuck] yes", "* ah [fuck] you", "* that [shit] bro",
      "* laura [fuck] you", "* actually oh [fuck]", "travis oh [shit] taliesin *", "your [shit] s",
      "oh [shit] marisha *", "travis oh [shit] matt *", "[shit] s already", "[fuck] hang on a second",
      "my [shit] s", "of [shit] s", "here [fuck] i", "oh [shit] let", "oh [shit] i'm gonna",
      "like [fuck] you i'm", "i [fucked] that one up", "shit up [shit]", "all right [fuck] it",
      "a little [bitch] i", "i'm like [fuck] it", "sam oh [shit] laura", "merch bunker no [shit]",
      "[shit] s * weird", "[fuck] it this *", "* [fuck] me dude", "* [fuck] it that's", "* [shit] robbie yeah",
      "* laura [fuck] marisha", "* taliesin [fuck] yes", "* travis [fuck] yes", "* travis [fuck] yeah",
      "* travis [fucking] a", "oh actually [fuck] *", "* okay no [shit]", "* luis oh [shit]",
      "i'd * like [fuck]", "me travis * [shit]", "yeah [fuck] it * it", "oh [fuck] thank you *",
      "oh [shit] laura oh *", "* was like [fuck] this", "the * ah [fuck] it", "a * oh [fuck] me",
      "* like have some [fucking]", "* said you're the [asshole]", "oh * liam oh [shit]", "oh boy * oh [shit]",
      "no no fuck * [fuck]", "oh [shit] i need to *", "* oh [shit] ashley", "[shit] s crazy", "* [fuck] you i",
      "* [fuck] it let's", "* [shit] s not", "and [shit] but *", "oh [shit] robbie *"
    ])),

    group("exact/context-windows/expanded", 1030, patterns([
      "hair is [fucking]", "[fucking] fabulous", "* oh [fuck] me", "* yeah [fuck] it", "his * is [fucking]",
      "* and [shit] and", "yeah [fuck] it *", "* [fuck] you all", "* ah [fuck] it", "[fuck] it we'll",
      "actually [fuck] it", "[fucking] gangster", "matt oh [shit]", "[fucking] meme", "[fucking] path",
      "brennan oh [shit]", "[fucking] * donut", "and [shit] * yeah", "and [shit] so *", "[fuck] it i'll *",
      "hold the [fuck] on", "get [shit] wrecked", "taliesin [fuck] it", "that [shit] back", "* and [shit] i",
      "like [fuck] man", "all * dumb [shit]", "[fucking] military", "[fuck] it we're", "send that [shit]",
      "travis oh [shit] ashley", "here * [fuck] you", "* and [shit] yeah", "sam oh [shit] *",
      "[fucking] phenomenal", "[cock] and balls", "[shit] * could do", "funniest [shit] * the",
      "just [fucking] * out", "* and [shit] it's", "you [fuck] you you *", "travis oh [shit] * oh",
      "like * hold the [fuck]", "* no [shit] yeah", "[fucking] hammered", "[fucking] broke",
      "[shit] wrecked and", "[fuck] it this", "[fuck] it but", "[shit] or whatever", "[fuck] you eli",
      "oh travis oh [shit]", "* [fucking] figure", "[fuck] it * do", "* [fuck] me i", "and [shit] * just",
      "* okay [fuck] it", "um * [fuck] it", "most * [shit] i've", "shout out * [fucking]",
      "there was a [fucking] *", "no no no no [fuck] *", "[fuck] sakes", "look like [shit] * the",
      "[fucking] stoked", "[fucking] useful", "[fucking] delight", "[fucking] ace", "[fuck] it yeah",
      "blow [shit]", "that [shit] bro", "buy this [shit]", "aabria oh [shit]", "here what's up [bitches]",
      "[fuck] you * that's", "and [shit] * he", "* right [fuck] it", "get * [shit] done", "give * [shit] he",
      "oh * [shit] matt", "like crazy [shit] *", "really no [shit] *", "and [shit] * i was",
      "you [fuck] you * you", "gonna [shit] in * mouth", "to the [fucking] * and", "get * the [fuck] out",
      "taliesin * laura oh [shit]", "like the * and [shit]", "one of * best [fucking]", "[fuck] me i *",
      "so * [fucked] up", "* really [fucked] up", "[fucking] steam", "[fucking] vehicle", "[fucking] communist",
      "[fucking] period", "[fucking] steep", "[fucking] retards", "[fucking] switch", "[fucking] horror",
      "[fucking] episodes", "[fuck] it go", "[fuck] you we're", "[fucked] up stuff", "[fuck] some up",
      "[fuck] them kids", "[fuck] it fuck it", "rolled [shit]", "matthew [fucking]", "to [fucking] take",
      "crazy [shit] that", "right [fuck] you", "sam [shit] matt", "not [fucking] it's", "taliesin [fuck] me",
      "to [fucking] be", "a [fucking] g", "and [shit] dude", "what [fucking] happens", "and [shit] too",
      "ashley [fuck] yes", "dude i [fucking]", "guns and [shit]", "rock that [shit]", "was like [fuck] yeah",
      "you're like [fuck] dude", "in like the [fucking]", "to go to the [fucking]", "[fucking] * van",
      "[fucking] videos *", "[fucking] photo *", "* [fucking] crazy", "you're [fucking] * it",
      "will [fucking] * you", "that [shit] * been", "little [fucking] * and", "a [fucking] * year",
      "and [shit] * get", "i'm [fucking] * it", "really [fucking] like *", "* hey [fuck] you", "a * [fuck] off",
      "what * [fuck] why", "close * [bitch] out", "laughter * [fuck] man", "because of [fucking] *",
      "god * a [fucking]", "it * ah [fuck]", "[fucking] * in the world", "oh [shit] i * my",
      "give a [fuck] that *", "this is * [shit] i", "like all the * [shit]", "* you you you [fuck] you",
      "just * don't give a [fuck]", "[fucking] hospital", "[fucking] loaded", "that [shit] if",
      "getting [fucked] by", "the dumb [shit] that", "[fucking] * or some", "[shit] and piss *",
      "got [fucked] over *", "* get [fucked] up", "if you * give a [shit]", "like [fuck] it *",
      "that dumb [shit]", "[fucking] lights", "[fucking] navy", "[fucking] gloves", "[fucking] chain",
      "[fucking] san", "[fucking] baller", "[fucking] goldberg", "[shit] alexander", "[fucking] dump",
      "[fucking] wizard", "[fucking] irritating", "[fucking] apartment", "[fucking] research",
      "[fucking] boxing", "[fucking] points", "[fucking] japanese", "[fucking] paint", "[fucking] hell's",
      "[fucking] punched", "[fucking] cameras", "[fucking] bread", "[fucking] golden", "[fucking] iron",
      "[fucking] douchebag", "[fucking] chicken", "[fucking] pole", "[fucking] slay", "[fucking] hideous",
      "[fucking] total", "[fucking] russian", "[fucking] whole", "[fucking] smashed", "[fucking] spear",
      "[fucking] gravity", "[fucking] cannon", "[fucking] california", "[fucking] lutely", "[fucking] mexican",
      "[fucking] tism", "[fucking] tube", "[fucking] e", "[fucking] ancient", "[fucking] la", "[fucking] knees",
      "[fucking] hero", "[fuck] it then", "[fuck] it we", "[shit] has been", "[shit] and people",
      "[fuck] you laughter", "[fuck] you but", "[shit] to it", "[fuck] me i'm", "[shit] travis oh",
      "[fuck] me sorry", "[fuck] i fucked up", "horrific [shit]", "bum [fuck]", "it [fucking] doesn't",
      "about [shit] and", "laura [fuck] yes", "oh [shit] luis", "i'm [fucking] going", "laughter [fuck] it",
      "that [fucking] big", "random [shit] that", "also [fuck] you", "laura [fuck] you", "liam [fuck] it",
      "also [fuck] your", "let's [fucking] let's", "he [fucking] goes", "like [fucking] 3", "if [shit] goes",
      "the [fuck] out i", "no [shit] and so", "i never [fucking]", "didn't know [shit]", "rocks and [shit]",
      "dude just [fucking]", "piece the [fuck]", "be really [fucking]", "get like [fucking]",
      "actually oh [fuck]", "you sneaky [bitch]", "oh actually [fuck]", "autistic as [fuck]", "is the [shit] i",
      "bunch of [shit] to", "oh no [shit] okay", "travis oh [shit] taliesin", "they're like [fuck] you",
      "he's like [fuck] you", "you cheeky little [shit]", "a really good [fucking]", "stopped giving a [fuck]",
      "[fucking] * oil", "[fucking] * pit", "[fucking] * kong", "[shit] laughs *", "[fucking] hill *",
      "[fucking] google *", "[fucking] tv *", "[fucking] autistic *", "[fucking] mission *",
      "[fucking] donkey *", "* [fucking] idiot", "[fucking] * to it", "[fucking] * or the",
      "[fucking] * or anything", "[shit] that * me", "[fuck] it that's *", "[fucked] up by *",
      "[fucking] give you *", "for [fucking] * years", "taliesin [fuck] * up", "just [fucking] * off",
      "oh [fuck] * man", "got [fucking] * up", "to [shit] * pants", "like [fuck] * should",
      "somebody [fucked] up *", "ah [fuck] you *", "the * [shit] was", "what * [fuck] so",
      "the * [fucking] part", "like * [fucking] big", "no * [fucked] up", "would * [fuck] with",
      "doing * [shit] and", "were * [shit] wrecked", "* two oh [fuck]", "boy * oh [shit]",
      "the * from [fucking]", "this and * [fucking]", "to him * [fucking]", "[fuck] * the fuck is",
      "i [fucking] i * it", "if i [fuck] * up", "in the [fucking] * and", "like a [fucking] * or",
      "in the [fucking] * right", "give a [shit] * a", "he's like [fuck] * he", "give a [fuck] * um",
      "like the [fucking] like *", "is the [shit] that *", "i was * [fuck] it", "all this * [shit] and",
      "laughter travis oh [shit] *", "they * like the [fucking]", "i * like i'm [fucking]",
      "thought * was a [fucking]", "i * about the [fucking]", "don't * is a [fucking]", "with the * and [shit]",
      "someone said * the [asshole]", "just just * that [shit]", "it sounds like * [fucking]",
      "it comes to * [shit]", "oh [fuck] what the fuck *", "[fucking] family", "[fucking] fault",
      "[fucking] bite", "[fucking] pink", "good [fucking] luck", "no [shit] really", "that [shit] from",
      "the [fucking] morning", "that [shit] got", "well [fuck] * i'm", "has * [fucked] up", "you * what [fuck]",
      "oh [shit] marisha", "travis oh [shit] matt", "[shit] all the time *", "[fucking] store",
      "[fucking] concept", "[fucking] iraq", "[fucking] abysmal", "[fucking] wind", "[fucking] dare",
      "[fucking] quick", "[fucking] corn", "[fucking] savage", "[fucking] shady", "[fucking] recording",
      "[fucking] blood", "[fucking] iowa", "[fucking] strike", "[fucking] halo", "[fucking] station",
      "[fucking] gigantic", "[fucking] main", "[fucking] days", "[fucking] animals", "[fucking] pocket",
      "[fucking] boot", "[fucking] obliterate", "[fucking] explosion", "[fucking] whiskey", "[fucking] apple",
      "[fucking] ballistic", "[fucking] gym", "[fucking] ears", "[fucking] cash", "[fucking] connect",
      "[shit] posting", "[fucking] lines", "[fucking] bombed", "[fucking] comment", "[fucking] horrific",
      "[fucking] wipe", "[fucking] wish", "[fucking] helicopter", "[fucking] blowing", "[fucking] season",
      "[fucking] mirror", "[fucking] razor", "[fucking] 200", "[fucking] flex", "[fucking] goal",
      "[fucking] tires", "[fucking] forget", "[fucking] wheels", "[fucking] fail", "[fucking] mall",
      "[fucking] numbers", "[fucking] failed", "[fucking] front", "[fucking] politicians", "[fucking] obsessed",
      "[fucking] imbeciles", "[fucking] jam", "[fucking] nicer", "[fucking] track", "[fucking] twitter",
      "[fucking] dirt", "[fucking] atrocious", "[fucking] depressing", "[fucking] homeless",
      "[fucking] cardboard", "[fucking] powerful", "[fucking] basement", "[fucking] views", "[fucking] reddit",
      "[fucking] questions", "[fucking] terror", "[fucking] furious", "[fucking] cuntskelleton",
      "[fucking] chunk", "[fucking] supermarket", "[fucking] prove", "[fucking] pc", "[fucking] peak",
      "[fucking] safe", "[fucking] adore", "[fucking] e3", "[fuck] activision", "[fucking] paths",
      "[fucking] mexico", "[fucking] guard", "[fucking] tanked", "[fucking] zombie", "[fucking] thing's",
      "[fucking] mastiff", "[fucking] j", "[fucking] desk", "[fucking] government", "[fucking] fab",
      "[fucking] community", "[fucking] fence", "[fucking] explain", "[fuck] you die", "[fuck] you well",
      "[fuck] me dude", "[fuck] just happened", "[fuck] okay no", "[fuck] him i", "[fuck] him so",
      "[shit] my own", "[fucked] up from", "[fucking] three years", "[fuck] me all", "[fuck] these people",
      "[shit] from back", "[fuck] you we", "[fuck] it do", "[fuck] it um", "[fucking] call of", "[fuck] you now",
      "[shit] robbie yeah", "[shit] smells like", "[fucking] taking it", "[fuck] me okay", "[shit] pushed in",
      "[fucking] c i", "[fuck] me you die", "[shit] i forgot my", "[shit] to you and", "[fuck] around and find",
      "[fuck] hang on a", "nerdiest [shit]", "hm [whore]", "stories [fucking]", "takes [fucking]", "ap [shit]",
      "funnest [shit]", "the [fuck] even", "this [fucking] table", "off [fuck] you", "um [fuck] it",
      "me [shitting] on", "some [shit] we", "jesus [fuck] dude", "i [bitch] about", "got [shit] wrecked",
      "laura [fuck] marisha", "no [shit] he", "you [fucking] freak", "you're [fucking] welcome",
      "one [fucking] dude", "nah [fuck] it", "that [shit] cuz", "no [shit] yes", "like [fucking] everything",
      "taliesin [fuck] yes", "like [fucking] 50", "oh [shit] who", "started [fucking] with",
      "these [fucking] games", "them [fuck] yeah", "like [fucking] jesus", "and [shit] from", "doing [shit] and",
      "and [shit] at", "just [fucking] let", "new [shit] and", "really [fucking] well", "again [fuck] you",
      "to [fuck] kids", "travis [fuck] yes", "travis [fuck] yeah", "the [fucking] new", "already [fucked] up",
      "like [fucking] 20", "like [fucking] 18", "travis [fucking] a", "you [fuck] you fuck",
      "yeah [fuck] yeah bro", "i [fucking] i love", "oh [shit] laura oh", "really [fucked] this one",
      "some [shit] but like", "as [fuck] oh yeah", "cameras and [shit]", "barrels and [shit]",
      "it had [fucking]", "follow the [fucking]", "luis oh [shit]", "marisha ah [shit]", "speed oh [fuck]",
      "just dumb [shit]", "and nobody [fucking]", "get into [fucking]", "bunker no [shit]", "pull a [fucking]",
      "a badass [bitch]", "of life [shit]", "do crazy [shit]", "fucking metric [shit]", "bothers the [fuck]",
      "legit as [fuck]", "love of [fucking] god", "bunch of [fucking] people", "know what's [fucked] up",
      "flip the [fuck] out", "are like [fuck] you", "looks like [shit] so", "you are [fucked] and",
      "was like [fuck] this", "he's like [fuck] and", "knocked the [fuck] out", "that this [shit] is",
      "cuz i [fucked] it", "with this [shit] i", "did i [fuck] that", "was like [fuck] i don't",
      "the level of [shit]", "never going to [fucking]", "i'd be like [fuck]", "so it's like [fuck]",
      "with like the [fucking]", "was in the [fucking]", "like have some [fucking]", "have like the [fucking]",
      "i'm gonna go [fuck]", "is a bad [bitch]", "me travis oh [shit]", "and he's just [fucking]",
      "yeah oh no [shit]", "how did i [fuck]", "said you're the [asshole]", "be cool as [shit]",
      "lot of dumb [shit]", "beautiful son of [bitch]", "and you're like [fuck] okay",
      "you're like holy [fuck] that", "don't give a [fuck] okay", "and then he just [fucking]",
      "i was like the [fuck]", "people to see the [fucked]", "do all kinds of [shit]",
      "one of my favorite [fucking]", "like i don't give a [fuck] about this", "[shit] * changing",
      "[fucking] * channel", "[fucking] * mon", "[fucking] gang *", "[fucking] mess *", "[fucking] monster *",
      "[fucking] mario *", "[fucking] bill *", "[fucking] gta *", "* [fucking] red", "* [fucking] kirby",
      "* [fucking] shower", "since [fucking] *", "witches * [bitches]", "electrician * [fucking]",
      "2009 * [fucking]", "spoil * [shit]", "[fucking] * them up", "[fucking] * going by",
      "[fucking] * with and", "[fuck] * shit but", "[fucking] * brennan yeah", "[shit] that's * really",
      "[shit] that * used", "[shit] from * in", "[fuck] with * too", "[fucking] people * the",
      "[fuck] this * of", "[shit] ever * you", "[fucking] done it *", "oh [shit] * about", "were [fucking] * up",
      "these [fucking] * are", "it's [fucking] * as", "i'm [fucking] * to", "yeah [fuck] * it's",
      "you're [fucking] * up", "do [shit] * the", "just [fucking] * everything", "little [shit] * just",
      "got [fucking] * got", "is [fucking] * of", "this [shit] * wild", "yeah [fuck] * what",
      "is [fucking] * up", "see [shit] * i", "some [fucking] * in", "that [fucking] * little",
      "yeah [fuck] * we'll", "looks [fucking] * it", "and [shit] * what", "liam [fuck] * up",
      "taliesin [fuck] * okay", "i [shit] on *", "yeah [fuck] this *", "yeah [fuck] me *", "travis [fuck] it *",
      "that [shit] gets *", "do [shit] and *", "travis [fuck] sam *", "* yeah [fuck] this", "* said [fuck] that",
      "* in [fucking] uh", "* gonna [fuck] up", "going * [fuck] you", "on * [fuck] me", "fuck * [fuck] it",
      "i'm * [shit] at", "love * [shit] and", "my * [fuck] it", "the * [fucking] hole",
      "we're * [fucking] around", "it * [fucking] gnarly", "go * [fuck] you", "course * [fucking] is",
      "a * [fucking] video", "want * [fucking] i", "love * [shit] it", "all * [shit] from", "the * [shit] too",
      "we'll * [fuck] it", "no * [fucking] didn't", "fine * [fuck] that", "they're * [fuck] they",
      "to * [fuck] him", "game * [fuck] that", "we * [fucking] make", "guy * [fucking] uh",
      "marisha * [shit] matt", "cool * [shit] like", "are getting [fucking] *", "okay no [shit] *",
      "* oh ah [fuck]", "do * dumb [shit]", "it * taliesin [fuck]", "taliesin * so [fucked]",
      "so * you're [fucking]", "the * went [fucking]", "sam * oh [shit]", "like * are [fucking]",
      "so * he [fucking]", "the * crazy [shit]", "when * just [fucking]", "thought * were [fucking]",
      "no liam * [shit]", "it liam * [shit]", "we went * [fucking]", "oh taliesin * [shit]", "bro i * [fucking]",
      "some cool * [shit]", "there with * [fucking]", "this needs * [fucking]", "a whole * [fucking]",
      "taliesin we're * [fucked]", "[shit] on the * and", "[fuck] i can't * the", "are [fucked] * you are",
      "the [fucking] the * the", "oh [fuck] yeah * i", "as [fuck] and * i", "the [fuck] on * you",
      "metric [shit] ton of *", "* like [fuck] you i'm", "to * [fuck] up the", "did * [fuck] that up",
      "this is [fucking] * oh", "he's a [fucking] * he", "travis oh [shit] * no", "like the [fucking] the *",
      "and * like [fuck] this", "i * the [fucking] the", "to * it [fuck] you", "up * you [fucked] up",
      "said * the [asshole] and", "is * the [fuck] out", "all * of [shit] and", "how * i [fuck] that",
      "of the * [shit] and", "the most * [fucking] things", "but it's a [fucking] *", "like that that [shit] *",
      "no no oh [fuck] *", "to * laura oh [shit]", "that * it was [fucking]", "and * was a [fucking]",
      "of * travis oh [shit]", "that * in the [fucking]", "i * all my [shit]", "the * are just [fucking]",
      "my * like a [fucking]", "a * and a [fucking]", "i got * and [shit]", "like he * a [fucking]",
      "like some * of [fucking]", "it's like * just [fucking]", "like that's * as [shit]",
      "they were * as [fuck]", "marisha oh * oh [shit]", "we were * like [fucking]", "do like the * [shit]",
      "to go on * [fucking]", "there's so much * [shit]", "it is a * [fucking]", "and now it's * [fucking]",
      "like i love * [shit]", "[fuck] what the fuck * the", "he * give a [fuck] about", "have a * of [shit] to",
      "don't know how * [shit] works", "with a lot of [shit] *", "it it * like the [fucking]",
      "i'm going to * a [fucking]", "i'm going to * to [fucking]", "that is the most * [shit]",
      "one of the most * [fucking]", "[fucking] offensive", "[fucking] ice cream", "same [shit] over",
      "a [fucking] vampire", "those are [fucking]", "you were a [fucking]", "a [fucking] * boy",
      "* get [fucked] over", "people * [shit] and", "they [fucked] up the *", "to * in the [fucking]",
      "something * [fucked] up", "oh [shit] ashley", "* you [fuck] you you", "like [fucking] uh",
      "no no no no [fuck]", "for * and [shit]", "* and [shit] but", "[fuck] em", "[fucking] gnarly",
      "laughter travis oh [shit]", "[fuck] that shit *", "the * [fucking] people", "and you're [fucking] *",
      "no [shit] * was", "* like [fuck] it", "[fucking] science", "[fucking] hat", "really no [shit]",
      "[fucking] freak *", "[fuck] you * yeah", "i [shit] myself *", "and all the * [shit]",
      "like one of * [fucking]", "[fuck] you i *", "[fucking] height", "some good [shit]", "[fucking] rides *",
      "loud as [fuck] *", "wait hold the [fuck]", "[fucking] table", "[fucking] stories", "[fucking] rules",
      "[fucking] color", "[fucking] important", "[shit] where like", "oh [shit] robbie", "that [shit] that's",
      "like 30 [fucking]", "the right [fucking]", "give a [fuck] that", "[fucking] controller *",
      "[fuck] it let's *", "i'm [fucked] up *", "metric [shit] ton *", "* of [shit] and", "* and [shit] like",
      "i * [shit] at", "these little [fuckers] *", "[fuck] you um", "[fucking] private *",
      "marisha * taliesin [shit]", "oh [shit] laura", "[fucking] autism", "[fucking] pokemon", "[fucking] photo",
      "[fucking] babies", "[fucking] tight", "[fucking] energy", "[fucking] really good", "[fuck] it fuck",
      "[fuck] it that's", "[fucked] up by", "[shit] myself i", "man [fuck] you", "to [fucking] just",
      "that [fucked] me up", "saw some [shit]", "like absolute [shit]", "was like [fuck] dude",
      "like the [fucking] like", "fuck you [fuck] you", "stealing [shit] *", "[fucking] * for this",
      "[fuck] it i *", "* [fuck] it i'm", "i'll [fucking] * you", "not [fucking] * you", "this [shit] * crazy",
      "it's [fucking] * like", "one * [fuck] it", "that's not [fucking] *", "laura * ashley [shit]",
      "okay * okay [fuck]", "my * taliesin [fuck]", "sam * laura [fuck]", "it has * [fucking]",
      "[fuck] it * going to", "[shit] and piss", "pocket [pussy]", "some * [shit] like", "[shit] ones",
      "[shit] you'll *", "[fucking] * and i'm like", "yeah * it's a [fucking]", "[shit] and i was like *",
      "[fucking] 40", "[fucking] tanks", "[fucking] combat", "[fucking] names", "[fucking] rage",
      "[fucking] south", "[fucking] bastard", "[fucking] problems", "[fucking] done it", "[fuck] you the",
      "[fuck] your mom", "[fuck] you fuck you", "nicest [fucking]", "dip [shit]", "greatest [fucking]",
      "i [shit] on", "same [shit] like", "laura [fuck] sam", "travis [fuck] it",
      "say [fuck] you", "two oh [fuck]", "it was cool as [shit]", "but i don't give a [fuck]",
      "[fucking] pool *", "[fucking] part *", "[fucking] * at it", "i'm [fucking] * for", "and [shit] * is",
      "it's [fucking] * the", "to [fucking] * about", "my [fucking] * on", "oh [fuck] * mean",
      "have [fucked] * up", "* well [fuck] you", "* me [fuck] you", "some * [shit] to", "not * [fuck] you",
      "do * [shit] and", "got your [fucking] *", "me some [fucking] *", "big ass [fucking] *",
      "dude * is [fucking]", "brennan * taliesin [fuck]", "dude * a [fucking]", "i [fucking] i * i",
      "the * [shit] i've ever", "like a [fucking] * like", "and you just [fucking] *", "the * sam oh [shit]",
      "oh * marisha oh [shit]", "sam oh * oh [shit]", "i * [shit] for", "* an [asshole]", "[fucking] respect",
      "[fucking] level", "[fuck] no laughter", "[fuck] you that's", "well no [shit]", "* [fucking] dope",
      "* [fucking] weird", "[shit] oh * shit", "was [fucking] * that", "to start [fucking] *",
      "a * of [fucking] people", "[fucking] video game", "sam oh [shit]", "anyway [fuck]", "oh [shit] taliesin",
      "* yeah [fuck] yeah", "the wrong [fucking] *", "travis * oh [shit]", "[shit] wrecked", "[fuck] that shit",
      "* like [fuck] yeah", "[fucking] work *", "nobody [fucking] *", "craziest [shit] *", "of [fucking] people",
      "and [shit] * like", "[shit] all the time", "travis oh [shit] *", "travis oh [shit]"
    ])),

    group("exact/context-windows/wildcard", 1070, [
      pattern`that's * [fucked] up`,
      pattern`this is * [fucked] up`,
      pattern`${["it's", "like", "yeah"]} * [fucked] up`,
      pattern`${["will", "to"]} [fuck] * up`,
      pattern`this [shit] * funny`,
      pattern`${["say", "said"]} [fuck] * and`,
      pattern`most * [shit] ever`,
      pattern`some really * [shit]`,
      pattern`${["i", "just", "don't"]} [fucking] * it`,
      pattern`[fuck] * wrong with`,
      pattern`figure * [shit]`,
      pattern`say some * [shit]`,
      pattern`oh [shit] * ${["did", "didn't"]}`,
      pattern`you're full of [shit]`,
      pattern`you're so full of [shit]`,
      pattern`you [fucked] up my`,
      pattern`yeah [fuck] me`,
      pattern`what [fuck] it`,
      pattern`ate [shit]`,
      pattern`${["do", "doing"]} dumb [shit]`,
      pattern`know jack [shit]`,
      pattern`${["couldn't", "didn't"]} see [shit]`,
      pattern`the [fuck] is going`,
      pattern`[shit] * pickle`,
      pattern`* [fucking] world`,
      pattern`[fucking] * world`,
      pattern`really * [fucked] up`,
      pattern`you know what [fuck]`,
      pattern`[fuck] * you ${["okay", "oh"]}`,
      pattern`of what the [fuck]`,
      pattern`you you you [fuck]`,
      pattern`don't * [fuck] this`,
      pattern`guy's * [fucking]`,
      pattern`guy's [fucking] *`,
      pattern`* [shit] they've`,
      pattern`* [fucking] light`,
      pattern`[fucking] * light`,
      pattern`[fuck] * okay maybe`,
      pattern`[fucking] look at me`,
      pattern`shut * [fuck] up`,
      pattern`can't * for [shit]`,
      pattern`a [fucking] * year old`,
      pattern`that [shit] because`,
      pattern`my [shit] list`,
      pattern`this [shit] is not`,
      pattern`this [shit] is * and`,
      pattern`not doing [shit]`,
      pattern`to * the same [shit]`,
      pattern`all the same [shit]`,
      pattern`[fucked] up part`,
      pattern`[fucking] quick *`,
      pattern`to [fucking] work`,
      pattern`[fucking] christ *`,
      pattern`shut the [fuck] up *`,
      pattern`just [fucking] * at`,
      pattern`i'm a bad [bitch]`,
      pattern`[fuck] this i`,
      pattern`[fuck] you you're`,
      pattern`going oh [shit]`,
      pattern`* this [fucking] movie`,
      pattern`you're [fucking] a`,
      pattern`[fucking] fool *`,
      pattern`outrageous [shit] *`,
      pattern`[fucking] dream *`,
      pattern`[shit] ain't * it`,
      pattern`[shit] you saw *`,
      pattern`oh [shit] * wow`,
      pattern`* i'm [fucking] out`,
      pattern`grab * by the [pussy]`,
      pattern`explain [shit]`,
      pattern`suck your * [cock]`,
      pattern`[fucking] ${["duh", "wanker"]}`,
      pattern`[pussy] hats`,
      pattern`[fuck] you dad`,
      pattern`time [shitting] on`,
      pattern`said [shit] about`,
      pattern`the [shit] about the`,
      pattern`that [fucking] smile`,
      pattern`game * like [shit]`,
      pattern`yeah [fuck] those`,
      pattern`no * [fuck] that`,
      pattern`[fucked] up * yeah`,
      pattern`you're [fucking] * to`,
      pattern`oh [shit] oh * i`,
      pattern`a [fucking] * for`,
      pattern`was * [fuck] you`,
      pattern`[fuck] yes * this`,
      pattern`you [fucking] * it`,
      pattern`don't [fuck] this *`,
      pattern`to sell * [shit]`,
      pattern`like they're * [fucking]`,
      pattern`oh [shit] * it's a`,
      pattern`got some * [shit] to`,
      pattern`[fucking] ${[
        "buy", "church", "closed", "laugh", "mistake", "news", "parents", "push",
        "section", "vampires"
      ]}`,
      pattern`${["heavy", "shooting the"]} [shit]`,
      pattern`[shit] comes out`,
      pattern`way the [fuck]`,
      pattern`just [fucking] don't`,
      pattern`don't give a [shit] about what`,
      pattern`oh [shit] ${["oh no", "oh god"]}`,
      pattern`[fuck] you no`,
      pattern`[shit] and * all`,
      pattern`the * i'm [fucking]`,
      pattern`a [fucking] * my`,
      pattern`um [fuck] * going`,
      pattern`and * [shit] they`,
      pattern`[bitch] isn't it`,
      pattern`[fuck] i tried`,
      pattern`keep [fucking]`,
      pattern`this [shit] ${["man", "i've"]}`,
      pattern`that [shit] should`,
      pattern`new [shit] i'm`,
      pattern`you're [fucked] the`,
      pattern`i [shit] myself and`,
      pattern`getting a [fucking]`,
      pattern`too oh [shit]`,
      pattern`[bitch] * getting out`,
      pattern`[fuck] me * i'm`,
      pattern`to * [shit] on`,
      pattern`${["this", "up"]} * [fucked] up`,
      pattern`okay * [fuck] yeah`,
      pattern`this * [fucking] rules`,
      pattern`hit * [motherfucker] in`,
      pattern`load of [shit] *`,
      pattern`this * extra [shit]`,
      pattern`kinds of * [shit]`,
      pattern`can see * [shit]`,
      pattern`will * the [shit] out`,
      pattern`[fuck] you * your`,
      pattern`some other * [shit]`,
      pattern`my [shit] yeah`,
      pattern`[shit] pulls`,
      pattern`[fuck] my face`,
      pattern`i'm [fuck] it`,
      pattern`in [shit] and`,
      pattern`my [shit] it`,
      pattern`${["have been", "is not"]} [fucking]`,
      pattern`[fucking] * rat`,
      pattern`here's * [fucking]`,
      pattern`[shit] i'm * saying`,
      pattern`is [fucking] * okay`,
      pattern`and * [shit] on`,
      pattern`some * [shit] ${["yeah", "you"]}`,
      pattern`they * just [fucking]`,
      pattern`and * are [fucking]`,
      pattern`the * just [fucking]`,
      pattern`to * this [fucker] and`,
      pattern`they * that [shit] in`,
      pattern`of all the * [shit]`,
      pattern`and * [shit] is`,
      pattern`[shit] i had`,
      pattern`that [shit] in the`,
      pattern`as * [fuck] you`,
      pattern`one * [shit] i`,
      pattern`[shit] what * we`,
      pattern`in [fucking] * i`,
      pattern`[shit] about that`,
      pattern`video [shit]`,
      pattern`oh [shit] where`,
      pattern`yes oh [shit]`,
      pattern`all right [fuck] i`,
      pattern`[fucking] dinner`,
      pattern`a sexist [asshole]`,
      pattern`some * [shit] in`,
      pattern`that's some * [shit]`,
      pattern`this [fucking] part`,
      pattern`that [shit] go`,
      pattern`some * [shit] that`,
    ]),

    group("exact/context-windows/extended", 1090, [
      pattern`said [fuck] it`,
      pattern`[fucking] ${["clowns", "shoes", "absurd", "toilet", "seasons", "dense", "illegal", "tragic", "ignorant", "jail", "prison", "dork", "body", "incredible", "difficult", "screaming", "lot", "psychopath", "delusional", "obvious", "matter", "smart", "get it", "times", "second", "retard", "pig", "strange", "nasty", "words", "roof"]}`,
      pattern`wreck [shit]`,
      pattern`[fuck] it if`,
      pattern`[fuck] this i'm`,
      pattern`them by the [pussy]`,
      pattern`like dog [shit]`,
      pattern`him the [fuck] out`,
      pattern`i need a [fucking]`,
      pattern`none of this [shit]`,
      pattern`[fuck] me it's`,
      pattern`sick son of a [bitch]`,
      pattern`${["but what the", "or whatever the", "wait what the", "yo what the"]} [fuck]`,
      pattern`get in the [fucking]`,
      pattern`saying dumb [shit]`,
      pattern`go [fuck] your`,
      pattern`[fuck] this and`,
      pattern`finally some good [fucking]`,
      pattern`${["doing", "did"]} [fuck] all`,
      pattern`stir [shit]`,
      pattern`${["give me a", "has no", "had no"]} [fucking]`,
      pattern`[shit] on for`,
      pattern`seeing [shit]`,
      pattern`don't [fuck] up`,
      pattern`doing [shit] like`,
      pattern`this [shit] makes`,
      pattern`who the [fuck] you`,
      pattern`[shit] from my`,
      pattern`where's my [fucking]`,
      pattern`what i [fucking]`,
      pattern`over a [fucking]`,
      pattern`the [fuck] you want`,
      pattern`that [shit] away`,
      pattern`[fucking] ${["alien", "chance", "do this", "dumbass", "hack"]}`,
      pattern`[shit] in ${["his", "our", "their"]}`,
      pattern`[fuck] it to`,
      pattern`[fuck] it. ${["they", "we"]}`,
      pattern`[fucking] legend`,
      pattern`[fuck] me ${["for", "money"]}`,
      pattern`[fucking] sex`,
      pattern`[shit] so ${["he", "we"]}`,
      pattern`[shit] ${["their pants", "they want to"]}`,
      pattern`[fucked] up you`,
      pattern`[fuck] yeah we`,
      pattern`[shit] you've`,
      pattern`a [fucking] take`,
      pattern`a [shit] ${["there", "they", "why"]}`,
      pattern`ah [shit] as`,
      pattern`ah [fuck] me`,
      pattern`ah [shit] ${["that", "you're"]}`,
      pattern`and ${["he", "she"]} [fucking]`,
      pattern`blowing [shit]`,
      pattern`crazy [shit] ${["but", "happened", "I", "I've", "in", "like", "so"]}`,
      pattern`for this [shit] ${["and", "my", "there", "you"]}`,
      pattern`gets [fucked] over`,
      pattern`give a [shit] ${["and", "but", "get", "is", "the", "you're"]}`,
      pattern`hey [fuck] it`,
      pattern`I'd [fuck]`,
      pattern`it's ${["his", "your"]} [fucking]`,
      pattern`just [fucked] ${["in the", "me"]}`,
      pattern`lot of [shit] ${["but", "from", "going on", "happened", "I", "in the", "on", "that", "yeah"]}`,
      pattern`make some [fucking]`,
      pattern`making that [shit]`,
      pattern`me me [fucking]`,
      pattern`mean [shit] ${["the", "you"]}`,
      pattern`nature [shit]`,
      pattern`need a [fucking]`,
      pattern`no [shit] ${["the", "to", "we", "yeah"]}`,
      pattern`of [shit] ${["at", "I've", "is", "it's", "like"]}`,
      pattern`of [fucked] me up`,
      pattern`of [shit] ${["so", "together", "we", "you're", "your"]}`,
      pattern`oh [shit] a`,
      pattern`said [fuck] that`,
      pattern`say that [shit]`,
      pattern`saying this [shit]`,
      pattern`serious [shit]`,
      pattern`so [fucked] and`,
      pattern`some [shit] ${["he", "she", "this"]}`,
      pattern`stole his [shit]`,
      pattern`that [shit] ${["ain't", "goes", "I'm", "too"]}`,
      pattern`the [shit] that ${["they", "we", "you"]}`,
      pattern`the [fuck] they want`,
      pattern`then [fuck] it`,
      pattern`this [shit] ${["as", "hurts", "isn't", "to", "yeah"]}`,
      pattern`throw [shit]`,
      pattern`to [fucking] stop`,
      pattern`to do [shit] ${["and", "in", "now"]}`,
      pattern`uh [fuck] me`,
      pattern`well [shit] ${["like", "that"]}`,
      pattern`what they [fucking]`,
      pattern`where the [fuck] he`,
      pattern`where's our [fucking]`,
      pattern`whole bunch of [shit]`,
      pattern`will [shit] ${["all", "down", "I"]}`,
      pattern`yeah [fuck] this`,
      pattern`? [fuck] ${["he", "it", "okay", "the"]}`,
      pattern`. [fuck] ${["if", "me", "the", "them", "they", "yeah"]}`,
      pattern`[fuck] it. he`,
      pattern`[shit] on our`,
      pattern`[fuck] well let's`,
      pattern`[fuck] you at`,
      pattern`a [fuck] i want`,
      pattern`absolute [fuck] up`,
      pattern`ah [fuck] ${["i'm", "oh", "okay", "yeah", "you"]}`,
      pattern`and [shit] ${["every", "for", "I'm", "if", "just", "oh", "right", "she", "went"]}`,
      pattern`are [fucking] kill`,
      pattern`are the [fucking]`,
      pattern`because [fuck] ${["i", "that", "them", "this", "you"]}`,
      pattern`but [shit] happens`,
      pattern`but [fuck] ${["i'm", "them", "those", "you"]}`,
      pattern`but she [fucking]`,
      pattern`deep [shit] you`,
      pattern`do the [fucking]`,
      pattern`doing [shit] so`,
      pattern`doing a [fucking]`,
      pattern`don't [fuck] ${["i", "my", "over"]}`,
      pattern`don't [fucking] tell`,
      pattern`don't give a [shit] ${["if", "in"]}`,
      pattern`even the [fucking]`,
      pattern`get [shit] off`,
      pattern`go [fuck] ${["it", "me", "no"]}`,
      pattern`have [shit] ${["on", "ton"]}`,
      pattern`her [shit] ${["i", "the"]}`,
      pattern`him [fuck] yeah`,
      pattern`his [shit] ${["get", "I'm", "to", "was"]}`,
      pattern`if you [fuck] ${["it", "with"]}`,
      pattern`is [fucking] with`,
      pattern`like [fuck] ${["it's", "my", "no", "the", "this", "what", "yeah", "your"]}`,
      pattern`like absolute [shit] ${["i", "what"]}`,
      pattern`looks like some [fucking]`,
      pattern`lot of [shit] well`,
      pattern`make a [fucking]`,
      pattern`man [fuck] ${["a", "all", "them"]}`,
      pattern`much [shit] ${["happened", "i", "in", "is", "oh", "on", "that", "to do"]}`,
      pattern`my [fucking] ${["rock", "son"]}`,
      pattern`nobody gave the [shit]`,
      pattern`not [fuck] over`,
      pattern`of [shit] on`,
      pattern`of [fuck] them`,
      pattern`oh [fuck] i'm going to`,
      pattern`oh [shit] some`,
      pattern`oh [fuck] to`,
      pattern`okay [fuck] ${["it", "the", "this", "you", "your"]}`,
      pattern`one [fuck] ${["that", "you"]}`,
      pattern`or [shit] i`,
      pattern`other [shit] ${["but", "going", "like", "that you", "to", "we", "you"]}`,
      pattern`put the [fucking]`,
      pattern`same [shit] ${["it's", "right", "we", "you"]}`,
      pattern`say [fuck] the`,
      pattern`some stupid [shit] too`,
      pattern`take any [shit]`,
      pattern`that [shit] ${["for", "or"]}`,
      pattern`that same [shit]`,
      pattern`that's the [shit] it's`,
      pattern`the [shit] again`,
      pattern`the [fucking] rock`,
      pattern`the [shit] that he`,
      pattern`their [shit] ${["and", "as", "i", "is", "out", "what"]}`,
      pattern`then [fuck] a`,
      pattern`they [shit] was`,
      pattern`this [fucking] rock`,
      pattern`to [shit] ${["I'm", "so", "they"]}`,
      pattern`tough [shit] ${["going", "the"]}`,
      pattern`want the [fucking]`,
      pattern`want to [fuck] my`,
      pattern`was [fucking] get`,
      pattern`where the [fuck] i'm going`,
      pattern`you [fucking] ${["ass", "good"]}`,
      pattern`you sick [fuck] ${["you", "your"]}`,
      pattern`your [shit] ${["again", "i", "out", "yeah", "you're"]}`,
      pattern`ah [shit] he`,
      pattern`and [shit] ${["ah", "uh"]}`,
      pattern`at this [shit] ${["every", "I", "right", "she", "the", "this"]}`,
      pattern`bunch of [shit] in`,
      pattern`but [shit] ${["all", "is", "it's"]}`,
      pattern`can [fuck] ${["all", "oh"]}`,
      pattern`don't [fuck] we`,
      pattern`dumb [shit] ${["i'm", "so"]}`,
      pattern`eat [shit] ${["get", "i'm"]}`,
      pattern`give a [fuck] ${["all", "i'm", "yeah", "your"]}`,
      pattern`have a [shit] for`,
      pattern`I'll [fuck] you`,
      pattern`a [fuck] your`,
      pattern`oh [shit] ${["we're", "they're"]}`,
      pattern`that [shit] the`,
      pattern`this [shit] it's`,
      pattern`oh [shit] she's`,
      pattern`? [fuck] we`,
      pattern`I'm [fucking] god`,
      pattern`jack [shit] ${["here", "so", "um"]}`,
      pattern`kind of [shit] ${["I", "she"]}`,
      pattern`like oh [shit] ${["here", "now", "yeah"]}`,
      pattern`make the [fucking]`,
      pattern`of that [shit] ${["it's", "why"]}`,
      pattern`of this [shit] ${["again", "all", "from", "is", "off", "she"]}`,
      pattern`oh [shit] ${["from", "in", "just", "right", "you know", "you're", "your"]}`,
      pattern`or [shit] ${["if", "what"]}`,
      pattern`own [shit] ${["and", "in", "right"]}`,
      pattern`right [fucking] get`,
      pattern`right [fuck] ${["it", "me", "no", "well"]}`,
      pattern`said [fuck] all`,
      pattern`say [shit] ${["I", "if", "out"]}`,
      pattern`so [fuck] ${["that", "the", "them", "well"]}`,
      pattern`stupid [shit] ${["but", "ever", "up"]}`,
      pattern`the [fuck] them`,
      pattern`well [fuck] ${["my", "off", "them"]}`,
      pattern`where the [fuck] i'm`,
      pattern`write this [shit] I`,
      pattern`you [fuck] ${["you guys", "you think"]}`,
      pattern`your [shit] well`,
      pattern`[fuck] boy`,
      pattern`and [shit] ${["she's", "they're"]}`,
      pattern`like oh [shit] I`,
      pattern`make [shit] they're`,
      pattern`oh [shit] now`,
      pattern`the [fuck] your`,
      pattern`to [fuck] my`,
      pattern`uh [shit] she's`,
      pattern`you sick [fuck]`,
      pattern`. [fuck] it`,
      pattern`did this [shit]`,
      pattern`like some [fucking]`,
      pattern`look [fucked] up`,
      pattern`this [shit] off`,
      pattern`got this [shit]`,
      pattern`[shit] starts`,
      pattern`and [shit] he`,
      pattern`oh [shit] he's`,
      pattern`his [shit] he`,
      pattern`oh [shit] like`,
      pattern`[fucking] business`,
      pattern`that [shit] she`,
      pattern`[fuck] that i'm`,
      pattern`uh [fuck] you`,
      pattern`[fuck] away`,
      pattern`[fucking] far`,
      pattern`what you [fucking]`,
      pattern`the [fuck] up`,
    ]),

    group("exact/fixed-expressions/general", 1040, [
      pattern`start with this [bullshit]`,
      pattern`holy [shit|fuck|fucking]`,
      pattern`this [shit] ${["happened", "was", "now"]}`,
      pattern`the rotten [asshole] of`,
      pattern`weird [fucked] up`,
      pattern`a [fucked] up`,
      pattern`your [shit] up`,
      pattern`some [fucking] sick`,
      pattern`do not [fuck] with`,
      pattern`${["none of that", "that kind of", "this kind of", "this type of", "that type of"]} [shit]`,
      pattern`${["crock", "pile", "sack", "piece", "pieces"]} of [shit]`,
      pattern`the actual [fuck]`,
      pattern`take a [shit]`,
      pattern`that [shit] ${["I", "but", "was", "to", "off", "is", "and", "as", "hurts", "down", "isn't", "show", "on", "like", "so"]}`,
      pattern`oh [shit] ${["this", "the", "oh my", "get", "is", "what's", "wow", "how", "um", "all", "so", "my bad"]}`,
      pattern`[shit] in my`,
      pattern`[shit] if something`,
      pattern`I was [fucking]`,
      pattern`is really [fucking]`,
      pattern`an ugly [bitch]`,
      pattern`[fuck] are you`,
      pattern`[shit] there was`,
      pattern`believe this [shit]`,
      pattern`oh [fuck] off`,
      pattern`put a [fucking]`,
      pattern`just just [fucking]`,
      pattern`feel like [shit]`,
      pattern`do that [shit]`,
      pattern`I'm not [fucking]`,
      pattern`he told [fucking]`,
      pattern`[fucked] up little`,
      pattern`own [shit] I`,
      pattern`I'm not no [asshole]`,
      pattern`man oh [shit]`,
      pattern`[fuck] yeah yes`,
      pattern`this [shit] I'm`,
      pattern`some [shit] ${["on", "that", "like", "you"]}`,
      pattern`to [fucking] get`,
      pattern`and just [fucking]`,
      pattern`going to get [fucking]`,
      pattern`games are [fucking]`,
      pattern`[shit] right and`,
      pattern`and [shit] on`,
      pattern`in case [shit]`,
      pattern`really [fuck] with`,
      pattern`[shit] and get`,
      pattern`a mind [fuck]`,
      pattern`about this [shit]`,
      pattern`[shit] in a`,
      pattern`believe that [shit]`,
      pattern`we should [fucking]`,
      pattern`can you just [fucking]`,
      pattern`oh [fucking] hell`,
      pattern`stupid [shit] that`,
      pattern`[shit] my pants`,
      pattern`am I [fucking]`,
      pattern`do the same [shit]`,
      pattern`[shit] is like`,
      pattern`[fuck] them I`,
      pattern`not give a [shit]`,
      pattern`give a [fuck] what`,
      pattern`got that [shit]`,
      pattern`too [fucking] far`,
      pattern`really give a [shit]`,
      pattern`do I have to [fucking]`,
      pattern`are a [fucking]`,
      pattern`look like a [fucking]`,
      pattern`through some [shit]`,
      pattern`this [shit] too`,
      pattern`of [shit] I'm`,
      pattern`direction oh [shit]`,
      pattern`like a bunch of [fucking]`,
      pattern`saying that [shit]`,
      pattern`and you [fucking]`,
      pattern`doing this [shit]`,
      pattern`this [shit] we`,
      pattern`you look [fucking]`,
      pattern`[fuck] that it's`,
      pattern`still a [fucking]`,
      pattern`did that [shit]`,
      pattern`in a [fucking]`,
      pattern`on the [fucking]`,
      pattern`be like [fuck]`,
      pattern`for that [shit]`,
      pattern`to [fuck] your`,
      pattern`to get some [pussy]`,
      pattern`I'm just [fucking]`,
      pattern`I'm like [fuck]`,
      pattern`out of [fucking]`,
      pattern`a [fucking] like`,
      pattern`I just [fucking]`,
      pattern`all your [shit]`,
      pattern`up your [fucking]`,
      pattern`a big [fucking]`,
      pattern`the [fuck] to`,
      pattern`me you [fucking]`,
      pattern`[shit] I want to`,
      pattern`of [shit] my`,
      pattern`[fucked] up this`,
      pattern`they're not [fucking]`,
      pattern`about that [shit]`,
      pattern`cuz I'm [fucking]`,
      pattern`from a [fucking]`,
      pattern`[fuck] am I`,
      pattern`a really [fucking]`,
      pattern`the [fuck] down`,
      pattern`I'm the [fucking]`,
      pattern`the [fuck] didn't`,
      pattern`it doesn't [fucking]`,
      pattern`over this [fucking]`,
      pattern`which is [fucking]`,
      pattern`[fuck] do I do`,
      pattern`I hate the [fucking]`,
      pattern`[shit] out of each`,
      pattern`game is [fucking]`,
      pattern`the [fuck] happened`,
      pattern`[fuck] away from`,
      pattern`that I'm [fucking]`,
      pattern`of [fucked] up`,
      pattern`yeah god [fucking]`,
      pattern`I am [fucking]`,
      pattern`much [shit] going`,
      pattern`[fucking] do that`,
      pattern`no god [fucking]`,
      pattern`having a [fucking]`,
      pattern`[shit] out of all`,
      pattern`sort of [shit]`,
      pattern`[shit] to me`,
      pattern`the [fuck] back`,
      pattern`the last [fucking]`,
      pattern`say [shit] ${["like", "about"]}`,
      pattern`some shady [shit]`,
      pattern`oh for [fuck's]`,
      pattern`guys [fuck] you`,
      pattern`the [asshole] for`,
      pattern`${["went", "goes", "turned", "turns"]} to [shit]`,
      pattern`make [shit] up`,
      pattern`${POSSESSIVE_DETERMINERS} [shit] together`,
      pattern`don't mean [shit]`,
      pattern`${["do", "doing", "saying"]} stupid [shit]`,
      pattern`[shit] here we go again`,
      pattern`a pocket [pussy]`,
      pattern`right [fucking] now`,
      pattern`won't do [shit]`,
      pattern`this [shit] happens`,
      pattern`jack [shit] about`,
      pattern`a [fucking] ${[
        "retard", "child", "dumbass", "legend", "disgrace", "rock", "grip", "chance",
        "vibrator", "douche", "weeb", "killer", "hack", "alien", "question"
      ]}`,
      pattern`[fucked] over by`,
      pattern`do jack [shit]`,
      pattern`a [shit] post`,
      pattern`I [fucking] loved`,
      pattern`[shit] hits the`,
      pattern`don't [shit] on`,
      pattern`a flying [fuck]`,
      pattern`[fuck] all about`,
      pattern`[shit] you're right`,
      pattern`people [bitch] about`,
      pattern`[shit] eating grin`,
      pattern`kinda [fucked] up`,
      pattern`[fuck] the people`,
      pattern`[shit] for brains`,
      pattern`your wet [pussy]`,
      pattern`saying [shit] ${["like", "about"]}`,
      pattern`my hard [cock]`,
      pattern`[shit] going on in`,
      pattern`pull that [shit]`,
      pattern`[fucked] in the ass`,
      pattern`losing his [shit]`,
      pattern`then [fuck] ${["you", "them"]}`,
      pattern`be [fucked] up`,
      pattern`[fuck] you talking`,
      pattern`done [fucked] up`,
      pattern`of [fucking] course`,
      pattern`no [shit] it's`,
      pattern`${["give", "gives"]} zero [fucks]`,
      pattern`[fuck] you money`,
      pattern`where's the [fucking]`,
      pattern`this [shit] ain't`,
      pattern`[fuck] anyone who`,
      pattern`[shit] in the woods`,
      pattern`a gorgeous [pussy]`,
      pattern`the [fuck] would`,
      pattern`yeah [fuck] that`,
      pattern`a basic [bitch]`,
      pattern`man [fuck] this`,
      pattern`a karma [whore]`,
      pattern`trying to start [shit]`,
      pattern`[fuck] those ${["people", "guys"]}`,
      pattern`downvoted to [shit]`,
      pattern`wanna [fuck] you`,
      pattern`[fuck] you if`,
      pattern`the [fuck] alone`,
      pattern`[shit] on the floor`,
      pattern`[fucked] up big`,
      pattern`gives no [fucks]`,
      pattern`it's my [fucking]`,
      pattern`even a [fucking]`,
      pattern`was talking [shit]`,
      pattern`[fucked] up thing`,
      pattern`freaked the [fuck]`,
      pattern`funniest [shit] I've`,
      pattern`calling [bullshit] on`,
      pattern`good little [slut]`,
      pattern`after all the [shit]`,
      pattern`but [fuck] that`,
      pattern`broken as [fuck]`,
      pattern`resting [bitch] face`,
      pattern`get [shit] on`,
      pattern`this [shit] show`,
      pattern`took a [shit]`,
      pattern`lose their [shit]`,
      pattern`to talk [shit]`,
      pattern`[fuck] all to`,
      pattern`the [asshole] in this`,
      pattern`your [pussy] looks`,
      pattern`[shit] compared to`,
      pattern`looked like [shit]`,
      pattern`can go [fuck]`,
      pattern`till you [cum]`,
      pattern`[fucking] listen to`,
      pattern`[shit] or get`,
      pattern`[cock] and ball`,
      pattern`[fucking] take it`,
      pattern`this kinda [shit]`,
      pattern`I'm [shit] at`,
      pattern`this [shit] when`,
      pattern`some bad [shit]`,
      pattern`doing that [shit]`,
      pattern`this [shit] all the`,
      pattern`gets [shit] on`,
      pattern`feeling like [shit]`,
      pattern`[shit] I forgot about`,
      pattern`an abusive [asshole]`,
      pattern`because [fuck] the`,
      pattern`[shit] beaten out`,
      pattern`just [fucking] stop`,
      pattern`go [fuck] yourselves`,
      pattern`just talking [shit]`,
      pattern`[fuck] the refs`,
      pattern`a chicken [shit]`,
      pattern`taste like [shit]`,
      pattern`the [fucking] puck`,
      pattern`[fucking] sex toy`,
      pattern`its [fucked] up`,
      pattern`[shit] its a`,
      pattern`mean jack [shit]`,
      pattern`you [fucking] retard`,
      pattern`but for [fucks] sake`,
      pattern`[pussy] and ass`,
      pattern`I'd [fuck] you`,
      pattern`nah [fuck] that`,
      pattern`[fuck] you mean`,
      pattern`my thick [cock]`,
      pattern`way too [fucking]`,
      pattern`throw [shit] at`,
      pattern`like [shit] for`,
      pattern`[shit] that makes`,
      pattern`corrupt as [fuck]`,
      pattern`[shit] the bed`,
      pattern`knows his [shit]`,
      pattern`are [shit] at`,
      pattern`no it [fucking]`,
      pattern`do [shit] ${["like", "for", "to", "so"]}`,
      pattern`[shit] went down`,
      pattern`ever the [fuck]`,
      pattern`played like [shit]`,
      pattern`mean [shit] if`,
      pattern`will [shit] on`,
      pattern`the [fuck] over`,
      pattern`loving [shit] out`,
      pattern`${["pulled", "post"]} this [shit]`,
      pattern`[shit] for them`,
      pattern`do you want to [fuck]`,
      pattern`to [bitch] about`,
      pattern`[fuck] you to`,
      pattern`don't do [shit]`,
      pattern`I the [asshole]`,
      pattern`you like [shit]`,
      pattern`of [shit] for`,
      pattern`that good [shit]`,
      pattern`I'd rather [fuck]`,
      pattern`[fuck] the warriors`,
      pattern`said [fuck] this`,
      pattern`listen here you little [shit]`,
      pattern`this [shit] goes`,
      pattern`dumb [shit] and`,
      pattern`call [bullshit] on`,
      pattern`[shit] show that`,
      pattern`is [fucking] trash`,
      pattern`he does this [shit]`,
      pattern`but [fuck] the`,
      pattern`off your [fucking]`,
      pattern`[shit] goes down`,
      pattern`stay the [fuck]`,
      pattern`say this [shit]`,
      pattern`to go [fuck]`,
      pattern`thank [fucking] god`,
      pattern`freak the [fuck]`,
      pattern`suck his [cock]`,
      pattern`you [fucking] son`,
      pattern`own [fucking] business`,
      pattern`seen a lot of [shit]`,
      pattern`gets [fucked] up`,
      pattern`that gay [shit]`,
      pattern`got [fucked] by`,
      pattern`whenever the [fuck]`,
      pattern`an attention [whore]`,
      pattern`piles of [shit]`,
      pattern`can [fuck] your`,
      pattern`to stir [shit]`,
      pattern`[fuck] them they`,
      pattern`much [shit] for`,
      pattern`wouldn't do [shit]`,
      pattern`making this [shit]`,
      pattern`me [fucking] sick`,
      pattern`is good [shit]`,
      pattern`blowing [shit] up`,
      pattern`this [shit] happen`,
      pattern`and [shit] will`,
      pattern`[fuck] yeah let's`,
      pattern`so [fuck] em`,
      pattern`[fuck] that noise`,
      pattern`i [fucking] wish`,
      pattern`they [shit] on`,
      pattern`getting [shit] done`,
      pattern`but [fuck] if`,
      pattern`saying [fuck] you`,
      pattern`how [fucking] good`,
      pattern`wherever the [fuck]`,
      pattern`can't hear [shit]`,
      pattern`get [fucked] and`,
      pattern`start no [shit]`,
      pattern`[fuck] them for`,
      pattern`other [shit] is`,
      pattern`[shit] i might`,
      pattern`bit [fucked] up`,
      pattern`kicking the [shit]`,
      pattern`is a bunch of [bullshit]`,
      pattern`those [fucked] up`,
      pattern`for [shitting] on`,
      pattern`say [fuck] a`,
      pattern`sick as [fuck]`,
      pattern`who [shit] in`,
      pattern`sacks of [shit]`,
      pattern`[shit] out of him`,
      pattern`read the [fucking]`,
      pattern`type of [shit]`,
      pattern`some serious [shit]`,
      pattern`[shit] to say`,
      pattern`[fuck] you in`,
      pattern`because this [shit]`,
      pattern`[shit] about me`,
      pattern`this [shit] so`
    ]),

    group("exact/fixed-expressions/conversation", 1050, [
      pattern`${["talking", "talk"]} [shit]`,
      pattern`like [fuck] it`,
      pattern`piss and [shit]`,
      pattern`if you [fuck] up`,
      pattern`${["being", "like", "and", "them", "been", "i", "be", "is", "you", "you're", "just", "was", "not", "of", "such", "he's", "are", "still", "me", "i'm", "what"]} an [asshole]`,
      pattern`that son of a [bitch]`,
      pattern`why the [fuck] you`,
      pattern`[fucking] ${["hilarious", "loser", "night", "dying", "children", "minds", "idea", "gay", "lazy", "brutal", "normal"]}`,
      pattern`[fuck] knows ${["why", "what", "how many"]}`,
      pattern`just kind of [fucking]$`,
      pattern`i'm a crazy [fucker]$`,
      pattern`[fucking] ${["years", "sick", "rat"]}`,
      pattern`where the [fuck] you`,
      pattern`where the [shit] starts`,
      pattern`of crazy [shit]`,
      pattern`[fucking] ${["loved", "spot", "break", "child", "stab"]}`,
      pattern`in deep [shit]`,
      pattern`[fucking] kill me`,
      pattern`to do this [shit]`,
      pattern`it [fucked] me up`,
      pattern`you don't know [shit]`,
      pattern`the [fuck] you think`,
      pattern`[fucking] ${["dollars", "blue"]}`,
      pattern`nobody gave a [shit]`,
      pattern`dirty as [fuck]`,
      pattern`[fuck] me you`,
      pattern`dumbest [shit] ever`,
      pattern`people don't give a [shit]`,
      pattern`and [shit] you know`,
      pattern`[fucking] ${["retarded", "prick", "clown", "delicious", "difference", "psycho", "dragons", "lame", "clue", "bullet", "handle", "scumbag", "destroy"]}`,
      pattern`doesn't mean [shit]`,
      pattern`[fuck] ups`,
      pattern`treated like [shit]`,
      pattern`so [fuck] it`,
      pattern`[slut] shaming`,
      pattern`a son of a [bitch]`,
      pattern`sexy as [fuck]`,
      pattern`[pussy] lips`,
      pattern`but [fuck] me`,
      pattern`[fuck] it and`,
      pattern`how the [fuck] you`,
      pattern`[fuck] it why`,
      pattern`well [fuck] me`,
      pattern`hear [shit]`,
      pattern`[shit] kicked`,
      pattern`did the same [shit]`,
      pattern`[fuck] it i'll`,
      pattern`remember [shit]`,
      pattern`smells like [shit]`,
      pattern`same [shit] for`,
      pattern`means [fuck] all`,
      pattern`[fuck] buddies`
    ]),

    group("exact/fixed-expressions/contextual", 1060, [
      pattern`type [shit]`,
      pattern`[shit] I can do`,
      pattern`pick ${["this", "up", "my"]} [shit]`,
      pattern`fun [shit] with`,
      pattern`on ${POSSESSIVE_DETERMINERS} [shit] list`,
      // Keep these phrase-specific; the corresponding bare frames are ambiguous.
      pattern`quit [fucking]`,
      pattern`is the kind of [shit]`,
      pattern`[fucking] ${["question", "phone"]}`,
      pattern`you [fucking] kidding`,
      pattern`no [fucking] way`,
      pattern`not giving a [shit]`,
      pattern`[shit] where you eat`,
      pattern`${["sucks", "sucks."]} [shit]`,
      pattern`you don't [fucking] ${["cheat", "jack off", "wink", "grab", "can", "smoke"]}`,
      pattern`${["hard", "weird", "violent", "sad"]} and [fucked] up`,
      pattern`that [shit] ${["makes", "turns", "calms", "pisses", "freaks"]} me`,
      pattern`oh [shit],`,
      // Keep wildcard contexts narrow.
      pattern`is that a [fucking]`,
      pattern`[fucking] special`,
      pattern`a * i'm [fucking]`,
      pattern`[shit] * in my pants`,
      // Compact fixed expressions.
      pattern`[fucking] ${["control", "interesting", "trust"]}`,
      pattern`${["same [shit] different", "same [shit], different"]}`,
      pattern`[shit] ${["just got real", "goes south"]}`,
      pattern`kicked the [shit]`,
      pattern`too [fucking] much`,
      pattern`right [fucking] here`,
      pattern`${["is [bullshit] and you know", "is [bullshit], and you know"]}`,
      pattern`[fucking] ${["milk", "psychic", "despise", "steal"]}`,
      pattern`get to the [fucking]`,
      pattern`${["oh [shit] wait", "oh [shit], wait"]}`,
      pattern`[fuck] that dude`,
      pattern`to [fucking] say`,
      pattern`some magic [shit]`,
      pattern`ah [fuck] this`,
      pattern`figure [shit] out`,
      pattern`to [bitch] slap`,
      pattern`of a [shit] about`,
      pattern`this [shit] is so`,
      pattern`of [shit] and`,
      pattern`[fucking] learn`,
      pattern`and [shit] i`,
      pattern`[fucking] ${[
        "excuse", "cat", "head", "nerd", "car", "space", "flies", "fight", "woman",
        "play", "fast", "run", "15", "rich", "random", "asked", "asking"
      ]}`,
      pattern`[shit] ${["i can't", "every time", "so you", "during"]}`,
      pattern`that [shit] up`,
      pattern`[fuck] everyone`,
      pattern`full [fucking]`,
      pattern`that [shit] yeah`,
      pattern`oh [shit] we`,
      pattern`why [fuck]`,
      pattern`19 [fucking]`,
      pattern`yep [fuck]`,
      pattern`${["nothing", "at"]} [fucking]`,
      pattern`gay [shit]`,
      pattern`crack [whore]`,
      pattern`and [shit] so`,
      pattern`green [shit]`,
      pattern`don't [fuck] this`,
      pattern`guy's [fucking]`,
      pattern`oh oh [shit] i`,
      pattern`and [shit] but`,
      pattern`oh [shit] i got`,
      pattern`[shit] they've`,
      pattern`[shit] at this`,
      pattern`[fuck] you what`,
      pattern`cult [shit]`,
      pattern`i give a [shit]`,
      pattern`patriarchal [bullshit]`,
      pattern`are they [fucking]`,
      pattern`all this crazy [shit]`,
      pattern`what the [fuck] is up with`,
      pattern`the [fuck] is up with`,
      pattern`what the [fucking] piece of`,
      pattern`whatever the [fuck] this`,
      pattern`there's a lot of [shit]`,
      pattern`learn [shit]`,
      pattern`the good [shit]`,
      pattern`just really [fucking]`,
      pattern`don't like that [shit]`,
      pattern`[fuck] you it's`,
      pattern`the [fuck] out of there`,
      pattern`don't [fucking] know`,
      pattern`[fucking] wrong`,
      pattern`[shit] going down`,
      pattern`let me [fucking]`,
      pattern`[fucking] move`,
      pattern`[shit] at you`,
      pattern`[fuck] it's okay`,
      pattern`than the [fucking]`,
      pattern`[fucking] true`,
      pattern`not be [fucking]`,
      pattern`he goes oh [shit]`,
      pattern`hey [fuck] you`,
      pattern`it's like oh [shit]`,
      pattern`do a [fucking]`,
      pattern`[fuck] is going on`,
      pattern`what the [fuck] i`,
      pattern`the [fuck] this`,
      pattern`you [fuck] you you`,
      pattern`[fucked] up is that`,
      pattern`[fucking] tell me`,
      pattern`because what the [fuck]`,
      pattern`[fuck] do we`,
      pattern`[fucking] mouth`,
      pattern`[shit] why are`,
      pattern`[shit] so if`,
      pattern`[shit] on that`,
      pattern`[shit] started`,
      pattern`put that [shit]`,
      pattern`say some [shit]`,
      pattern`of other [shit]`,
      pattern`[fuck] okay maybe`,
      pattern`beats the [shit]`,
      pattern`[shit] was crazy`,
      pattern`[fucked] by a`,
      pattern`[fuck] you okay`,
      pattern`gave a [shit]`,
      pattern`[fuck] you you you`,
      pattern`a little [fuck] boy`,
      pattern`[fuck] oh yeah oh`,
      pattern`him [fuck] you guys`,
      pattern`[fuck] no yeah`,
      pattern`like oh [shit] i'm`,
      pattern`[fucking] model`,
      pattern`okay okay okay [fuck]`,
      pattern`[fuck] i'm going to cast`,
      pattern`right [fuck] my`,
      pattern`okay no [shit]`,
      pattern`oh [shit] you've`,
      pattern`want a [fucking]`,
      pattern`and [shit] they`,
      pattern`[shit] and they`,
      pattern`losing their [shit]`,
      pattern`the [fuck] that is`,
      pattern`kick the [shit]`,
      pattern`just [fucking] with me`,
      pattern`this [shit] they`,
      pattern`[shit] out of her`,
      pattern`[fucking] kidding`,
      pattern`that [shit] just`,
      pattern`looks like a [fucking]`,
      pattern`cute [shit]`,
      pattern`said some [shit]`,
      pattern`the [fuck] i want`,
      pattern`[shit] about them`,
      pattern`[shit] behind`,
      pattern`these sick [fucks]`,
      pattern`that [shit] what`,
    ]),

    group("exact/fixed-expressions/idioms", 1080, [
      pattern`${["ah", "aw"]} [shit] here we`,
      pattern`${["ah", "aw"]} [shit], here we`,
      pattern`not the [asshole]$`,
      pattern`the same [shit]$`,
      pattern`grow the [fuck] up`,
      pattern`permission to [cum] on your`,
      pattern`be the [asshole]$`,
      pattern`by the [pussy]$`,
      pattern`on earth [dipshit]$`,
      pattern`chill the [fuck] out`,
      pattern`[fuck] me I`,
      pattern`a beautiful [pussy]$`,
      pattern`${["on my", "around my"]} [cock]$`,
      pattern`playing like [shit]$`,
      pattern`to do [shit]$`,
      pattern`[fuck] yeah I`,
      pattern`[fuck] you for`,
      pattern`lost my [shit]$`,
      pattern`some stupid [shit]$`,
      pattern`so much [shit]$`,
      pattern`like absolute [shit]$`,
      pattern`[shit] like that`,
      pattern`talking mad [shit]`,
      pattern`which is [bullshit]$`,
      pattern`the [fuck] you say`,
      pattern`me the [fuck] out`,
      pattern`have a [shit] load of`,
      pattern`love to [cum] all over`,
      pattern`shut your [whore] mouth`,
      pattern`get that [shit] outta here`,
      pattern`don't know [shit]`,
      pattern`can't see [shit]`,
      pattern`${["lose your", "lose my"]} [shit|fucking]`,
      pattern`zero [fucking] deaths`,
      pattern`${["who", "nobody", "no one"]} gives a [fuck|shit] about`,
      pattern`weird [fucking] statue`,
      pattern`eat [shit] and die`,
      pattern`sweet [fuck] all`,
      pattern`[fuck] all$`,
      pattern`for the love of [fuck]`,
      pattern`^[fuck] knows`,
      pattern`${[".", "!", "?"]} [fuck] knows`,
      pattern`[shit] hit the fan`,
      pattern`${["that", "bad", "nature", "and"]} [shit] happens`,
      pattern`[shit] out of luck`,
      pattern`tough [shit] if`,
      pattern`^[fuck] this`,
      pattern`${[".", "!", "?"]} [fuck] this`,
      pattern`${[".", "!", "?"]} [fuck|shit] that`,
      pattern`${["no", "zero"]} [fucks] given`,
      pattern`${["give one", "give a single"]} [fuck]`,
      pattern`give two [fucks]`,
      pattern`[shit] storm`,
      pattern`pure [fucking] respect`,
      pattern`piece of [fucking] ass`,
      pattern`piece of [fucking] [shit]`,
      pattern`write this [shit|fucking] down`,
      pattern`stole my [shit|fucking]`,
      pattern`apply that [shit]`,
      pattern`${["live for", "redoing", "struggle at"]} this [shit]`,
      pattern`respect women and [shit]`,
      pattern`all this [shit] again`,
      pattern`delete your [shit]`,
      pattern`pathetic little [moron|bitch]`,
      pattern`a [shit|fucking|fuck] ton`,
      pattern`that's the [shit] right there`,
      pattern`the whole [fucking] …`,
      pattern`bull [fucking] [shit]`,
      pattern`${EVALUATIVE_NOUN_PREFIXES} [bullshit]`,
      pattern`political [bullshit|shit]`,
      pattern`[bullshit] ${EVALUATIVE_NOUN_SUFFIXES}`,
      pattern`make some [fucking] noise`,
      pattern`zero [fucks].`,
      pattern`[fuck] yeah dude`,
      pattern`[fuck] it ${["I'm", "let's", "I"]}`,
      pattern`[fuck] it. ${["I'm", "let's", "I"]}`,
      pattern`${["yeah", "but", "ah", "say", "I'll"]} [fuck] it`,
      pattern`oh [fuck] me`,
      pattern`freaking the [fuck]`,
      pattern`what the [fuck's] going on`,
      pattern`what the [fuck's] happening`,
      pattern`what the [fucking] hell`,
      pattern`I have no [fucking]`,
      pattern`to [fucking] kill`,
      pattern`empty the [shitter]`,
      pattern`use the [shitter] as much`,
      pattern`cool [shit]`,
      pattern`see that [shit]`,
      pattern`oh [shit] ${["that's", "and"]}`,
      pattern`[fuck] you I'm`,
      pattern`any of this [shit|fucking]`,
      pattern`any of that [shit]`,
      pattern`a whole bunch of [shit|bullshit]`,
      pattern`got [shit] all over`,
      pattern`have [shit] to do`,
      pattern`the [shit] that I`,
      pattern`[shit] that I have`,
      pattern`uh well [shit]`,
      pattern`she did a [bullshit]`,
      pattern`stay down [bitch]`,
      pattern`what the absolute [fuck]`,
      pattern`cluster [fuck]`,
      pattern`is such [bullshit]$`,
      pattern`you sick [fuck|fucker]$`,
      pattern`${["play dead", "play dead,"]} [bitch]$`,
      pattern`[fuck] the police`
    ])
  ]);


  var exports = EXACT_RULES;

  root.UncensoredRuleDataParts = root.UncensoredRuleDataParts || {};
  root.UncensoredRuleDataParts.exact = exports;
  if (typeof module === "object" && module.exports) module.exports = exports;
})();
